version: '3.8'

services:
  coturn:
    image: coturn/coturn:4.6.2
    container_name: fuselink-turn
    restart: unless-stopped
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/udp"
      - "5349:5349/tcp"
      - "49152-65535:49152-65535/udp"
    volumes:
      - ./coturn.conf:/etc/coturn/turnserver.conf:ro
    command: ["-c", "/etc/coturn/turnserver.conf"]
    networks:
      - fuselink

networks:
  fuselink:
    driver: bridge